"""Stable application-facing BizMan core boundary."""

from bizman.core.assets import AssetId, RepositoryAssets
from bizman.core.collection import CollectionRequest, CollectionResult, collect
from bizman.core.context import CoreContext
from bizman.core.detection import DetectionRequest, DetectorRunSummary, detect_changes
from bizman.core.errors import (
    AssetError,
    BizManError,
    ConfigurationError,
    ContractMismatchError,
    DataIntegrityError,
    OperationError,
)
from bizman.core.read import (
    ChangeGetRequest,
    ChangeGetResult,
    ChangeListRequest,
    ChangePage,
    ChangeRecord,
    KnowledgeGetRequest,
    KnowledgeGetResult,
    KnowledgeHit,
    KnowledgeItem,
    KnowledgeResolveRequest,
    KnowledgeResolveResult,
    KnowledgeSearchRequest,
    KnowledgeSearchResult,
    SessionGetRequest,
    SessionGetResult,
    SessionListRequest,
    SessionPage,
    SessionRecord,
    get_change,
    get_knowledge,
    get_session,
    list_changes,
    list_sessions,
    resolve_knowledge,
    search_knowledge,
)
from bizman.core.time import SystemUtcClock, UtcClock
from bizman.core.validation import ValidationResult, validate_repository


__all__ = [
    "AssetError",
    "AssetId",
    "BizManError",
    "ChangeGetRequest",
    "ChangeGetResult",
    "ChangeListRequest",
    "ChangePage",
    "ChangeRecord",
    "CollectionRequest",
    "CollectionResult",
    "ConfigurationError",
    "ContractMismatchError",
    "CoreContext",
    "DataIntegrityError",
    "DetectionRequest",
    "DetectorRunSummary",
    "KnowledgeGetRequest",
    "KnowledgeGetResult",
    "KnowledgeHit",
    "KnowledgeItem",
    "KnowledgeResolveRequest",
    "KnowledgeResolveResult",
    "KnowledgeSearchRequest",
    "KnowledgeSearchResult",
    "OperationError",
    "RepositoryAssets",
    "SessionGetRequest",
    "SessionGetResult",
    "SessionListRequest",
    "SessionPage",
    "SessionRecord",
    "SystemUtcClock",
    "UtcClock",
    "ValidationResult",
    "collect",
    "detect_changes",
    "get_change",
    "get_knowledge",
    "get_session",
    "list_changes",
    "list_sessions",
    "resolve_knowledge",
    "search_knowledge",
    "validate_repository",
]
