"""Deterministic read-only market analytics observations."""

from bizman.market.model import (
    COVERAGE_OBSERVED,
    MAX_HTML_CHARS,
    MAX_ROWS,
    MarketContractError,
    RetailMarketCityPage,
    RetailMarketGroupRow,
    RetailPriceCityRow,
    RetailPriceGroupPage,
    SCHEMA,
    SURFACE_RETAILMARKET_CITY,
    SURFACE_RETAILPRICES_GROUP,
    SURFACE_VENDORS,
    VendorCatalogPage,
    VendorProductRow,
    market_page_fingerprint,
    market_page_semantics,
    market_page_surface,
)
from bizman.market.parsers import parse_market_page
from bizman.market.projection import (
    PROJECTION_SCHEMA,
    MarketProjection,
    MarketProjectionEntry,
    build_market_projection,
    decode_payload,
)
from bizman.market.store import (
    APPLICATION_ID,
    DEFAULT_READ_LIMIT,
    MAX_READ_LIMIT,
    MIN_SQLITE_VERSION,
    SURFACES,
    USER_VERSION,
    MarketObservationRecord,
    MarketStore,
    MarketStoreCompatibilityError,
    MarketStoreConflictError,
    MarketStoreError,
    MarketStoreIntegrityError,
    MarketStoreOperationError,
)


__all__ = [
    "APPLICATION_ID",
    "COVERAGE_OBSERVED",
    "DEFAULT_READ_LIMIT",
    "MAX_HTML_CHARS",
    "MAX_READ_LIMIT",
    "MAX_ROWS",
    "MIN_SQLITE_VERSION",
    "PROJECTION_SCHEMA",
    "MarketContractError",
    "MarketObservationRecord",
    "MarketProjection",
    "MarketProjectionEntry",
    "MarketStore",
    "MarketStoreCompatibilityError",
    "MarketStoreConflictError",
    "MarketStoreError",
    "MarketStoreIntegrityError",
    "MarketStoreOperationError",
    "RetailMarketCityPage",
    "RetailMarketGroupRow",
    "RetailPriceCityRow",
    "RetailPriceGroupPage",
    "SCHEMA",
    "SURFACE_RETAILMARKET_CITY",
    "SURFACE_RETAILPRICES_GROUP",
    "SURFACE_VENDORS",
    "SURFACES",
    "USER_VERSION",
    "VendorCatalogPage",
    "VendorProductRow",
    "build_market_projection",
    "decode_payload",
    "market_page_fingerprint",
    "market_page_semantics",
    "market_page_surface",
    "parse_market_page",
]
